name: CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t rdvisionuat/crmbackend .
      - name: Publish image to Docker Hub
        run: docker push rdvisionuat/crmbackend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Pull Image from Docker Hub
        run: sudo docker pull rdvisionuat/crmbackend:latest
      - name: Stop old container if exists
        run: sudo docker stop springboot-example-container || true
      - name: Remove old container if exists
        run: sudo docker rm springboot-example-container || true
      - name: Run new container
        run: sudo docker run -d -p 80:8080 --name springboot-example-container rdvisionuat/crmbackend:latest
